### ISSUE TITLE
Reset css is overkill?

### ISSUE THREAD

**Issue by ChrisARaymond** [alecrios/core#1]
I like the simplicity of how you have implemented a responsive grid, but I think your using a total reset actually will create more complexity as someone will have to then restyle everything just to get started, meaning, writing a whole lot of css.

It seems like the industry consensus is that a reset that removes everything is not terribly useful. Instead, folks seem to have moved to normalize.css.

Obviously this is a personal choice. But for those of us who don't wish to use your reset, I would suggest that you indicate in your unminified stylesheet where your reset properties are so that those of us who don't wish to use that can quickly remove it and use our own approach.

Thanks!

**Comment by alecrios** [comment]
Hi Chris,

The reset vs normalize issue is something I debated with quite a bit. Ultimately, I decided to go against the general consensus in favor of the way I like to work personally. I like to start with as clean a slate as possible so that I always know that every style present on the page is my own. This definitely requires more lines of CSS, and this isn't how most people like to work, but I think this is great for those who are extremely meticulous.

With that said, I do plan on adding more documentation to the unminified stylesheet, and as I do that, I'll be sure to indicate what is the grid and what is the reset. That way, if you'd like to only use a portion, you can do so easily.

Thanks,
Alec

**Comment by ChrisARaymond** [comment]
Hi Alec,

Thanks, of course it makes sense to develop something the way you like to work! Thanks for the response.
